<?php
/**
 * Title: Privacy Policy
 * Slug: iykra/privacy-policy
 * Categories: privacy
 * Block Types: core/template-part/privacy-policy-page
 * Description: Privacy Policy page.
 *
 * @package WordPress
 * @subpackage IYKRA
 * @since IYKRA 1.0
 */

?>

<!-- wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"0"}}}} -->
<main>
    <div class="bg-white">
        <div class="mx-auto sm:px-0 lg:px-14">
            <div class="flex isolate px-8 py-8 lg:px-14 lg:py-8">
                <div class="grid gap-14 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2">
                    <div class="flex flex-col justify-between ">
                        <div class="pt-14 text-left space-y-4 gs_reveal gs_reveal_fromLeft">
                            <p class="iykra-sg text-5xl lg:text-6xl text-black">Privacy and Policy</p>
                            <h1 class="iykra-gs text-lg lg:text-xl text-black">Last updated: April 30, 2025</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mx-auto sm:px-0 lg:px-14">
            <div class="flex isolate px-8 py-8 lg:px-14">
                <div class="grid gap-14 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 pb-14">
                    <div class="sm:col-span-1 md:col-span-2 lg:col-span-2 space-y-2">
                        <h2 class="iykra-sg text-xl lg:text-2xl">Interpretation and Definitions</h2>
                        <h2 class="iykra-gs text-lg lg:text-xl">Interpretation</h2>
                        <p class="iykra-gs text-sm lg:text-base">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                        <h2 class="iykra-gs text-lg lg:text-xl">Definitions</h2>
                        <p class="iykra-gs text-sm lg:text-base">For the purposes of this Privacy Policy:</p>
                        <ul class="list-disc ml-8">
                            <li class="iykra-gs text-sm lg:text-base"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Company</strong> refers to PT Pusat inovasi Nusantara, Sopo Del Tower, 22nd Floor Jl. Mega Kuningan Barat III, Lot 10. 1-6 Kawasan Mega Kuningan Jakarta Selatan 12950.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Country</strong> refers to: Indonesia.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Service</strong> refers to the Website.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>Website</strong> refers to IYKRA, accessible from https://iykra.com.</li>
                            <li class="iykra-gs text-sm lg:text-base"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Collecting and Using Your Personal Data</h2>
                        <h2 class="iykra-gs text-lg lg:text-xl">Types of Data Collected</h2>
                        <h4 class="iykra-gs text-base lg:text-lg"><strong>Personal Data</strong></h4>
                        <p class="iykra-gs text-sm lg:text-base">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                        <ul class="list-disc ml-8">
                            <li class="iykra-gs text-sm lg:text-base">Email address</li>
                            <li class="iykra-gs text-sm lg:text-base">First name and last name</li>
                            <li class="iykra-gs text-sm lg:text-base">Phone number</li>
                            <li class="iykra-gs text-sm lg:text-base">Address, State, Province, ZIP/Postal code, City</li>
                        </ul>
                        <h4 class="iykra-gs text-base lg:text-lg"><strong>Usage Data</strong></h4>
                        <p class="iykra-gs text-sm lg:text-base">Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                        <p class="iykra-gs text-sm lg:text-base">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                        <h4 class="iykra-gs text-base lg:text-lg"><strong>Information from Third-Party Social Media Services</strong></h4>
                        <p class="iykra-gs text-sm lg:text-base">The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                        <ul class="list-disc ml-8">
                            <li class="iykra-gs text-sm lg:text-base">Google</li>
                            <li class="iykra-gs text-sm lg:text-base">Facebook</li>
                            <li class="iykra-gs text-sm lg:text-base">Instagram</li>
                            <li class="iykra-gs text-sm lg:text-base">Twitter</li>
                            <li class="iykra-gs text-sm lg:text-base">LinkedIn</li>
                        </ul>
                        <p class="iykra-gs text-sm lg:text-base">If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Tracking Technologies and Cookies</h2>
                        <p class="iykra-gs text-sm lg:text-base">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Use of Your Personal Data</h2>
                        <p class="iykra-gs text-sm lg:text-base">The Company may use Personal Data for the following purposes:</p>
                        <ul class="list-disc ml-8">
                            <li class="iykra-gs text-sm lg:text-base">To provide and maintain our Service, including to monitor the usage of our Service.</li>
                            <li class="iykra-gs text-sm lg:text-base">To manage Your Account: to manage Your registration as a user of the Service.</li>
                            <li class="iykra-gs text-sm lg:text-base">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                            <li class="iykra-gs text-sm lg:text-base">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                            <li class="iykra-gs text-sm lg:text-base">To provide You with news, special offers and general information about other goods, services and events.</li>
                            <li class="iykra-gs text-sm lg:text-base">For business transfers: We may use Your information to evaluate or conduct a merger, restructuring, or other sale of Our assets.</li>
                            <li class="iykra-gs text-sm lg:text-base">For other purposes: We may use Your information for data analysis, identifying usage trends, improving our Service.</li>
                        </ul>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Retention of Your Personal Data</h2>
                        <p class="iykra-gs text-sm lg:text-base">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Transfer of Your Personal Data</h2>
                        <p class="iykra-gs text-sm lg:text-base">Your information, including Personal Data, may be transferred to, and maintained on, computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Disclosure of Your Personal Data</h2>
                        <h2 class="iykra-gs text-lg lg:text-xl">Business Transactions</h2>
                        <p class="iykra-gs text-sm lg:text-base">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>
                        <h2 class="iykra-gs text-lg lg:text-xl">Law Enforcement</h2>
                        <p class="iykra-gs text-sm lg:text-base">Under certain circumstances, the Company may be required to disclose Your Personal Data if required by law or in response to valid requests by public authorities.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Security of Your Personal Data</h2>
                        <p class="iykra-gs text-sm lg:text-base">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Children's Privacy</h2>
                        <p class="iykra-gs text-sm lg:text-base">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Links to Other Websites</h2>
                        <p class="iykra-gs text-sm lg:text-base">Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Changes to this Privacy Policy</h2>
                        <p class="iykra-gs text-sm lg:text-base">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                        <h2 class="iykra-sg text-xl lg:text-2xl pt-4">Contact Us</h2>
                        <p class="iykra-gs text-sm lg:text-base">If you have any questions about this Privacy Policy, You can contact us:</p>
                        <ul class="list-disc ml-8">
                            <li class="iykra-gs text-sm lg:text-base">By email: contact@iykra.com</li>
                            <li class="iykra-gs text-sm lg:text-base">By visiting this page on our website: https://iykra.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- /wp:group -->